### ISSUE TITLE
Date range filter component

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#360]
Investigate the viability of and implement a date range componet for the `updated` filters on the Datasets and Analyses pages, for use with #283

**Comment by frewmack** [comment]
Material UI officially only offers date range pickers as part of their 'Enterprise' commercial package: https://next.material-ui.com/components/date-range-picker/

There's a knockoff datetime range picker available here: https://github.com/jkslyby/material-ui-datetime-range-picker, but it looks like there isn't a way to disable the time portion and only select dates. It does show that it's possible to re-create it using non-commercial components in Material UI.

**Comment by kevinlul** [comment]
A single [picker](https://material-ui.com/components/pickers) is free, but ranges are more complicated. I also found non-MUI packages [react-date-range](https://github.com/hypeserver/react-date-range) and Airbnb's [react-dates](https://github.com/airbnb/react-dates) (likely unmaintained and depends on moment.js anyway)

**Comment by frewmack** [comment]
The knockoff datetime range picker I found from [jkslyby](https://github.com/jkslyby/material-ui-datetime-range-picker) is almost certainly not worth using. Other than the fact that it's just two datetime pickers side-by-side, it has so many dependencies that are hardly worth including for this one component.
```
success Saved 22 new dependencies.
info Direct dependencies
└─ material-ui-datetime-range-picker@1.0.0
info All dependencies
├─ bowser@1.9.4
├─ chain-function@1.0.1
├─ change-emitter@0.1.6
├─ convert-css-length@2.0.1
├─ css-in-js-utils@2.0.1
├─ encoding@0.1.13
├─ fbjs@0.8.17
├─ inline-style-prefixer@3.0.8
├─ isomorphic-fetch@2.2.1
├─ keycode@2.2.0
├─ lodash.find@4.6.0
├─ lodash.merge@4.6.2
├─ lodash.throttle@4.1.1
├─ material-ui-datetime-range-picker@1.0.0
├─ node-fetch@1.7.3
├─ normalize-scroll-left@0.2.1
├─ parse-num@1.0.0
├─ react-addons-update@15.6.3
├─ react-event-listener@0.4.5
├─ recompose@0.24.0
├─ simple-assign@0.1.0
└─ ua-parser-js@0.7.23
```
