### ISSUE TITLE
Add detailed logging to backend

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#361]
We currently have SQLAlchemy logs and the default Flask per-request logs in Apache-ish style. If something goes awry, we have little information to debug from the logs besides the response code. This is a decently large issue but otherwise easy issue to add logging (via the native Python logging module or `app.logger`) to aid in debugging production faults.

We can split this up into smaller items to be easier to code and review.

**Comment by delvinso** [comment]
to keep track of modules which are currently being worked on/or are finished 
- [ ] analyses.py (overfetch WIP?)
- [ ] buckets.py
- [ ] datasets.py (overfetch WIP?)
- [ ] families.py 
- [ ] groups.py
- [ ] participants.py 
- [ ] routes.py 
- [ ] tissue_samples.py
- [ ] users.py 

unsure if utils.py, madmin.py require logging?
