### ISSUE TITLE
Keycloak: Configure keycloak login page to display multiple identity providers

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#737]
Give Stager users the option to login with a federated identity provider (such as Auth0) or via the IDP offered by Keycloak itself.

Edit: it  seems that this task mainly concerns keycloak configuration and doesn't involve source code changes. If this is the case, this issue can be closed when the appropriate documentation is updated.

**Comment by samuelkimuli** [comment]
Is it possible to use something like FreeIPA (https://www.freeipa.org/page/Main_Page) with this kind of implementation? Can it be integrated into keycloak?

**Comment by frewmack** [comment]
> Is it possible to use something like FreeIPA (https://www.freeipa.org/page/Main_Page) with this kind of implementation? Can it be integrated into keycloak?

Keycloak has a dedicated section in their docs for integrating with FreeIPA, so this looks promising: https://www.keycloak.org/docs/6.0/server_admin/#_sssd
