### ISSUE TITLE
Minio: upgrade to latest version

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#775]
This [minio release](https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z) changed how the file browser and console work. The browser was deprecated in favor of the console, and the console port must be set explicitly or else a "random" port will be chosen and users will be redirected there. If this port isn't accessible, then the redirection won't work. A few things (possibly among others) that we need to do before we can upgrade:

1. update configurations in all environments (local, CHEO-RI, stager-dev) so that a console port is stipulated explicitly.
2. update any relevant nginx configurations
3. confirm that the console can do everything that the browser currently does and/or update configurations so that console works as we'd like it to. Specifically, non-admin users should be able to view their buckets and have the proper read/write permissions for their buckets in place. 

In the meantime, minio should be clamped at `minio/minio:RELEASE.2021-06-17T00-10-46Z` to ensure expected behavior.

**Comment by samuelkimuli** [comment]
One issue i have noticed regarding option 2. is that with the console both the admin and  non admin user cannot download an object to their local machine . An error occurs when you do this " site cannot be reached", this is not the case with the usual browser. That type of functionality seems to be working fine with the browser.

**Comment by samuelkimuli** [comment]
The current plan on the  console is set to be updated to the latest release,  so yes it is the latest

**Comment by cklamann** [comment]
Ah, OK -- I wonder if that's the issue -- if the minio server is clamped on the 6-17 version and the console is the latest version, they might be incompatible? In any case, we'll need to set up some kind of testing environment for the upgrade, since the latest minio version bundles the console and we won't need to host it separately anymore (as far as I understand): https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z.
