### ISSUE TITLE
Create script to post reports to PhenoTips variant store

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#869]
The script should take a report csv path as input and do the following:
- transform report into long format and separate into separate 'reports' for each participant
- fetch an API token from PT using a client key and secret
- post each participant-level report to the PT variant store endpoint 

NB: We currently don't have the specific endpoint for the token or post request that we'll be using, but the script should be written in such a way that we can drop them in when they're available.

This code should go into a new repository, as it's not part of the Stager application, though we'll be tracking progress here for convenience.

**Comment by delvinso** [comment]
Consolidated into #1021
