### ISSUE TITLE
Create script to post reports to Stager

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#870]
Depends on #869 

The script should take a report csv path and an analysis ID (?) as input and do the following:
 - transform report into long format and separate into separate 'reports' for each participant (see #869)
 - break up each participant-level 'report' into json that corresponds to the appropriate Stager data models (i.e., separate data that belongs in the `variant` table from data that belongs in the `genotype` table). 
 - fetch an API token from Stager using a client key and secret
 - post the data to Stager (we might want to write an endpoint like `api/analysis/{id}/report` that wraps both inserts in a transaction).

This script should go in the same repo as #869.

**Comment by delvinso** [comment]
Consolidated into #1021
