### ISSUE TITLE
OIDC: Research implementation details

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#936]
Here are some questions that should be answered in detail before we choose/move ahead with an OIDC solution
#### Stager integration
- [x] Are any code changes required to use existing OIDC code to facilitate identity brokering (see Mackenzie's [comment](https://github.com/ccmbioinfo/stager/issues/673#issuecomment-862671459))? If so what are they? 
- [x] What steps must be taken to migrate current users to Keycloak? Can this be accomplished using existing scripts?
#### Stager/Minio integration:
- [x] Can a client in the same realm as one or more Minio instances use its user_id token to get temporary credentials for a Minio user?
- [x] What is the procedure for storing and updating policies?
- [x] How much refactoring of current Minio-admin code would be required to move to an STS-based flow?
- [x] Can we house users of disparate Minio instances in a single realm without additional security measures?

**Comment by kevinlul** [comment]
Links from CanDIG:
- https://candig-github-io.pages.dev/posts/candigv2-aai/
- https://candig-github-io.pages.dev/posts/gentle-intro-to-federated-distributed-authz/

**Comment by cklamann** [comment]
>Are any code changes required to use existing OIDC code to facilitate identity brokering (see Mackenzie's comment)? If so what are they?

I was able to add a test Auth0 account to Keycloak's Identity Providers, and I successfully attempted to login to Stager using an existing Auth0 user's credentials. With the current code, a new Auth0 user will be denied access to Stager b/c their subject/issuer IDs are not in the Stager user database. However, a record of the new user will be added to the Keycloak user store on first login, meaning that an admin could at this point add that user to the Stager DB. So it is possible to enable brokering with no code changes, though the flow would be awkward for the user. At the least, we'd probably want to alert the new user that their login 'request' has be received and is being processed. Code changes would be needed to for more fine-grained control (e.g., mapping the new user to an existing user based on email, automatically creating a record for the new user in the Stager DB based on white list, etc)

**Comment by cklamann** [comment]
>  What steps must be taken to migrate current users to Keycloak? Can this be accomplished using existing scripts?

This is also very straightforward. There is already a [click command](https://github.com/ccmbioinfo/stager/blob/master/flask/app/manage_keycloak.py#L320) to add an existing user to keycloak. By wrapping a call to the underlying function in another click command that calls the function for every active user, I was able to import the Stager users into Keycloak's user store and successfully log in using their credentials.

**Comment by cklamann** [comment]
> Can a client in the same realm as one or more Minio instances use its user token to get temporary credentials for a Minio user?

Yes, this works as advertised, although there are a few details to be aware of. Most importantly, the web app client needs to have the Minio `policy` user attribute mapped to a claim on the id token (just like the Minio clients), and it must also include the Minio client(s) in its audience mappings or the jwt will be rejected.

**Comment by cklamann** [comment]
>  Can we house users of disparate Minio instances in a single realm without additional security measures?
Provisionally, this seems like it would be fine. Policies are stored in the Minio instance and an admin can grant one or more of these policies by updating a user's `policy` attribute in Keycloak. We just have to ensure that there is no overlap between policy names for users who should have access to only one instance supported by the realm. For example, if we grant a user the builtin `readwrite` policy in Keycloak, that user will be able to log into the console of any Minio instance that depends on Keycloak, since `readwrite` is (by default) a valid policy on every instance. One way to avoid this may be to use namespacing, e.g. instead of `readwrite` we have `LABX_readwrite`, which is identical to `readwrite` but only exists on LABX's Minio instance and thus won't grant access to LABZ's data.

**Comment by cklamann** [comment]
> What is the procedure for storing and updating policies?

Keycloak's admin API allows for `POST`ing new users, and policies can be added/updated with a `PUT` call. For instance, the following uses the bearer token of the realm service account (with admin privileges) to grant the `readwrite` policy to the user with ID `0c87cb6c-1667-49d1-9e4f-d790eb3b8a80`:
```
curl --location --request PUT 'http://localhost:9090/auth/admin/realms/minio/users/0c87cb6c-1667-49d1-9e4f-d790eb3b8a80' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <...>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "attributes": {"policy": ["readwrite"]},
}'
```

**Comment by cklamann** [comment]
> How much refactoring of current Minio-admin code would be required to move to an STS-based flow?

1. A lot of the functionality in madmin.py would need to be reimplemented:
	  a. group policies would need to become user policies; [oidc does not support group policies](https://docs.min.io/minio/baremetal/security/openid-external-identity-management/external-authentication-with-openid-identity-provider.html#access-control-for-externally-managed-identities)
	  b. policy creation code would need to target specific minio instances (to create policies, need credentials for a user who has admin role for all minio instances supported by the realm) 
	  c. user management would need to use keycloak api
2. For listing files, we'd need to fetch the user's temporary credentials and determine which minio instance they have access to (from token).
3. Create a flow for new users.
4. Decide how much user data to store in keycloak and update User model accordingly.
5. Depending on above, might also make sense to use the [react-keycloak adapter](https://github.com/react-keycloak/react-keycloak) for the front-end and set up a bearer-only client for the backend.

**Comment by kevinlul** [comment]
It does look like on the track for maximum MinIO integration with OIDC that we would need to alter the relationship with Stager from Stager administering it to Stager simply working with it.
