### ISSUE TITLE
Flask: post analysis metadata to PhenoTips 

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#949]
We'd like to store analysis metadata in phenotips and associate it with a patient record. The data will be posted via the PT API with the participant's external id (`<familyCodename>_<participantCodename>`) used to fetch the internal id. The first step might be a click command that will post the following for a given participant (actual endpoint is not ready yet, so this is mostly a planning task). It needs to be determined what file metadata is available, because I think there might an interest in `bam`s and `cram`s as well as `vcf`s, `csv`s, etc. There might need to be some intermediate steps to get this data into Stager if it doesn't exist.
 1. analysis_type
 2. analysis_date
 3. analysis_tissue_type
 4. analysis_files[]
     - name
     - type

**Comment by delvinso** [comment]
Currently analysis metadata is stored implicitly in `analysis.result_paths`. It is expected that the result path is updated in Stager upon completion of an analysis, although not all completed analyses have a result path in the db. If dataset-level metadata is required to be stored and shared with Phenotips, such as .vcf and .bams, it would not be a simple task as these files would need to be identified on a dataset level by traversing the result paths and then mapped back into the database. Furthermore these result paths are not guaranteed to be constant over time as data will eventually be moved from dccforge to CHEO-RI space.

**Comment by delvinso** [comment]
Consolidated into #1021
