### ISSUE TITLE
SQLAlchemy: Upgrade to version 1.4 

### ISSUE THREAD

**Issue by jennyziyi-xu** [ccmbioinfo/stager#956]

**Comment by kevinlul** [comment]
[Old branch I had locally on this topic](/ccmbioinfo/stager/tree/kevinlul/sqlalchemy-1.4)
[Merged with latest](/ccmbioinfo/stager/tree/kevinlul/sqlalchemy-1.4-rebased)

**Comment by jennyziyi-xu** [comment]
Yes, I merged from your branch: https://github.com/ccmbioinfo/stager/tree/kevinlul/sqlalchemy-1.4-rebased
