### ISSUE TITLE
React/Flask: Fix more issues in Participant table

### ISSUE THREAD

**Issue by jennyziyi-xu** [ccmbioinfo/stager#960]
- [x] The column `dataset_type` does not filter properly in `Participant` table. 
- [x] Make the field `family_codename` editable in the rows of the `Participant` table. 
- [x] If we edit a row in the `Participant` table, save the results, navigate to another page, then navigate back to the `Participant` table, the stale data will be shown instead of fresh data.

**Comment by kevinlul** [comment]
Is this issue resolved?

**Comment by jennyziyi-xu** [comment]
Yes!
